apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-crt
spec:
  secretName: {{ .Values.certificate.secret_name }}
  dnsNames:
  - {{ .Values.domain.url }}
  issuerRef:
    name: {{ .Values.issuer.name }}
    kind: {{ .Values.issuer.kind }}
    group: cert-manager.io